SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES 
FROM BOOK_SALES s
INNER JOIN BOOK b ON s.BOOK_ID = b.BOOK_ID
INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE s.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;