SELECT T1.MEMBER_NAME, T2.REVIEW_TEXT, DATE_FORMAT(T2.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE T1
JOIN REST_REVIEW T2 ON T1.MEMBER_ID = T2.MEMBER_ID 
WHERE T1.MEMBER_ID
IN (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID
   HAVING COUNT(*) = (SELECT MAX(REVIEW_COUNT) FROM (SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT FROM REST_REVIEW GROUP BY MEMBER_ID) AS RESULT))
ORDER BY REVIEW_DATE, REVIEW_TEXT;