SELECT YEAR(T2.SALES_DATE) AS YEAR, MONTH(T2.SALES_DATE) AS MONTH, COUNT(DISTINCT T2.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT T2.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO T1
JOIN ONLINE_SALE T2 ON T1.USER_ID = T2.USER_ID
WHERE YEAR(T1.JOINED) = 2021
GROUP BY YEAR(T2.SALES_DATE), MONTH(T2.SALES_DATE)
ORDER BY YEAR, MONTH;