SELECT HISTORY_ID,
        ROUND((((100 - IF(DISCOUNT_RATE IS NULL, 0, DISCOUNT_RATE)) * DAILY_FEE) * DAYS) / 100, 0) AS FEE
FROM (
    SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DAYS, (SELECT MAX(DISCOUNT_RATE) FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = C.CAR_TYPE AND REPLACE(DURATION_TYPE, '일 이상', '') <= (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
    ) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) H
ORDER BY FEE DESC, HISTORY_ID DESC;